- name: do config file for dnsmasq
  template:
    dest: /etc/dnsmasq.conf
    src: dnsmasq.conf.j2
  register: dnsmasq_systemd

- name: restart dnsmasq if config changed
  service:
    name: dnsmasq
    state: restarted
  when: dnsmasq_systemd.changed

- name: ensure dnsmasq service enabled and started
  service:
    name: dnsmasq
    enabled: yes
    state: started

- name: do config file for pxelinux
  template:
    dest: /tftpboot/pxelinux.cfg/default
    src: pxelinux-default.j2

- name: do config file for ignition on the pxe booted CoreOS
  template:
    dest: /srv/http/coreos/pxe-ignition.json
    src: pxe-ignition.json

- name: do systemd unit file for darkhttpd with proper settings
  template:
    dest: /etc/systemd/system/darkhttpd.service
    src: darkhttpd.service
  register: darkhttpd_systemd

- name: reload systemd if files changed
  command: systemctl reload-daemon
  when: darkhttpd_systemd.changed

- name: restart darkhttpd if config changed
  service:
    name: darkhttpd
    state: restarted
  when: darkhttpd_systemd.changed

- name: ensure darkhttpd service enabled and started
  service:
    name: darkhttpd
    enabled: yes
    state: started
